// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEO5sW4fcAR3FsVFnEX54QBVu2ESiTWg',
    appId: '1:177802175710:web:b0ad48f00c15855fc74e4f',
    messagingSenderId: '177802175710',
    projectId: 'blogapp-6e6c5',
    authDomain: 'blogapp-6e6c5.firebaseapp.com',
    storageBucket: 'blogapp-6e6c5.appspot.com',
    measurementId: 'G-6EYEBNZ1N6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtUM5XvWrRgHVrM-cCrOzR4nZAM13McXQ',
    appId: '1:177802175710:android:5c2127ed0e09e758c74e4f',
    messagingSenderId: '177802175710',
    projectId: 'blogapp-6e6c5',
    storageBucket: 'blogapp-6e6c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq84o5Pu7u0mHXpvdynM6TPDxDlhejj_8',
    appId: '1:177802175710:ios:1742852cc47d0e5dc74e4f',
    messagingSenderId: '177802175710',
    projectId: 'blogapp-6e6c5',
    storageBucket: 'blogapp-6e6c5.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq84o5Pu7u0mHXpvdynM6TPDxDlhejj_8',
    appId: '1:177802175710:ios:1742852cc47d0e5dc74e4f',
    messagingSenderId: '177802175710',
    projectId: 'blogapp-6e6c5',
    storageBucket: 'blogapp-6e6c5.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEO5sW4fcAR3FsVFnEX54QBVu2ESiTWg',
    appId: '1:177802175710:web:78349f34383f7d19c74e4f',
    messagingSenderId: '177802175710',
    projectId: 'blogapp-6e6c5',
    authDomain: 'blogapp-6e6c5.firebaseapp.com',
    storageBucket: 'blogapp-6e6c5.appspot.com',
    measurementId: 'G-ED991GCQ55',
  );
}
